version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      # - borboletas:/var/lib/postgresql/data
      - ./ops/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=senhaserver
      - POSTGRES_USER=server
      - POSTGRES_DB=borboletas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 30

# volumes:
#   borboletas:
