services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - borboleta:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=borboleta
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 30
    deploy:
      resources:
        limits:
          memory: 512M   # Set memory limit to 512 MB
          cpus: "0.5"    # Limit to half a CPU core

volumes:
  borboleta:
